general:
  debug: false
  instance_name: "searxng"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true
  open_metrics: ''
brand:
  new_issue_url: https://github.com/searxng/searxng/issues/new
  docs_url: https://docs.searxng.org/
  public_instances: https://searx.space
  wiki_url: https://github.com/searxng/searxng/wiki
  issue_url: https://github.com/searxng/searxng/issues
search:
  safe_search: 0
  autocomplete: ""
  autocomplete_min: 4
  default_lang: "auto"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html
    - json
server:
  port: 8080
  bind_address: "0.0.0.0"
  base_url: false
  limiter: false
  public_instance: false
  secret_key: "example"
  image_proxy: false
  http_protocol_version: "1.0"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer
redis:
  url: false
ui:
  static_path: ""
  static_use_hash: false
  templates_path: ""
  default_theme: simple
  default_locale: ""
  query_in_title: false
  infinite_scroll: false
  center_alignment: false
  theme_args:
    simple_style: auto
outgoing:
  request_timeout: 30.0
  max_request_timeout: 40.0
  pool_connections: 200
  pool_maxsize: 50
  enable_http2: false
  retries: 5
engines:
  - name: sogou
    engine: sogou
    shortcut: sogou
  - name: sogou images
    engine: sogou_images
    shortcut: sogoui
  - name: sogou videos
    engine: sogou_videos
    shortcut: sogouv
  - name: sogou wechat
    engine: sogou_wechat
    shortcut: sogouw
  - name: bing
    engine: bing
    shortcut: bi
  - name: bing images
    engine: bing_images
    shortcut: bii
  - name: bing news
    engine: bing_news
    shortcut: bin
  - name: bing videos
    engine: bing_videos
    shortcut: biv
  - name: baidu
    baidu_category: general
    categories: [general]
    engine: baidu
    shortcut: bd
  - name: baidu images
    baidu_category: images
    categories: [images]
    engine: baidu
    shortcut: bdi
  - name: baidu kaifa
    baidu_category: it
    categories: [it]
    engine: baidu
    shortcut: bdk
  - name: 360search
    engine: 360search
    shortcut: 360so
  - name: 360search videos
    engine: 360search_videos
    shortcut: 360sov
  - name: acfun
    engine: acfun
    shortcut: acf
  - name: bilibili
    engine: bilibili
    shortcut: bil
  - name: chinaso news
    chinaso_category: news
    engine: chinaso
    shortcut: chinaso
  - name: chinaso images
    chinaso_category: images
    engine: chinaso
    shortcut: chinasoi
  - name: chinaso videos
    chinaso_category: videos
    engine: chinaso
    shortcut: chinasov
doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'
  doai.io: 'https://dissem.in/'
  sci-hub.se: 'https://sci-hub.se/'
  sci-hub.st: 'https://sci-hub.st/'
  sci-hub.ru: 'https://sci-hub.ru/'
default_doi_resolver: 'oadoi.org'

